<a href="https://colab.research.google.com/github/Anaju7/Anaju7/blob/main/Aula_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Aula 4 - Coleções  30/09/2024

##Tuplas

Usar tuplas para montar estruturas de dados heterogêneos

In [ ]:
tupla = ('Hillux', 'Corolla', 'SW4')
tupla[0]

'Hillux'

In [ ]:
for item in tupla:
  print(item)

Hillux
Corolla
SW4


##Listas

As listas devem ser usadas para dados homogêneos.

In [ ]:
lista = ['item1', 'item2', 'item3']

In [ ]:
lista.append("item4")
print(lista)

['item1', 'item2', 'item3', 'item4']


In [ ]:
# percorrer a lista
for item in lista:
  print(item)

item1
item2
item3
item4


## Dicionarios

In [ ]:
carros = {'hillux': 300.000,
          'sw4': 400.000,
          'corola': 350.000
          }
print(carros['sw4'])

400.0


In [ ]:
carros['yaris'] = 300.000
print(carros)

{'hillux': 300.0, 'sw4': 400.0, 'corola': 300.0, 'yaris': 300.0}


In [ ]:
del(carros)['yaris']
print(carros)

{'hillux': 300.0, 'sw4': 400.0, 'corola': 300.0}


In [ ]:
print(carros.items())
print(carros.keys())
print(carros.values())

dict_items([('hillux', 300.0), ('sw4', 400.0), ('corola', 300.0)])
dict_keys(['hillux', 'sw4', 'corola'])
dict_values([300.0, 400.0, 300.0])


## Conjuntos

In [ ]:
c1 = {1,2,3,4,5}
c2 = {4,5,6,7,8}
print(c1.union(c2))
print(c1.intersection(c2))
print(c1.difference(c2))

{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{1, 2, 3}


## Matrizes


* precisa de biblioteca para trabalhar com arrays e matrizes **Numpy**

In [ ]:
# importando biblioteca
import numpy as np

array = np.array([1,2,3,4,5])

matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matriz)
# numero de linhas e colunas
print(matriz.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
# percorrendo matriz
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    print(matriz[i][j], end=' ')
  print("")

1 2 3 
4 5 6 
7 8 9 


# Aula 5 - 01/10/2024

## questão 1

In [ ]:
num = 0
lista = []
while num < 5:
  num = num + 1
  lista.append(num)
print(lista)

[1, 2, 3, 4, 5]


In [ ]:
soma = 0
for item in lista:
  soma = soma + item
print(soma)

15


## Questão 2

In [ ]:
alunos = {'aluno1': 7,
          'aluno2': 6,
          'aluno3': 5}
somanotas = 0
for aluno, nota in alunos.items():
  print(f'aluno: {aluno} com nota : {nota}')
  somanotas = somanotas + nota
print(f'media da turma é: {somanotas / 3}')


aluno: aluno1 com nota : 7
aluno: aluno2 com nota : 6
aluno: aluno3 com nota : 5
media da turma é: 6.0


## Questão 3

In [ ]:
import numpy as np
soma = 0
matriz = np.array([[3,4,1],[3,1,5]])
print(matriz)

for a in range(matriz.shape[0]):
  for b in range(matriz.shape[1]):
    soma = soma + matriz[a][b]
print(soma)

[[3 4 1]
 [3 1 5]]
17
